### ISSUE TITLE
关于caffe动态库和静态库的问题

### ISSUE THREAD

**Issue by graysonliu** [10km/caffe-static#2]
同样是ssd的代码，make之后自动生成libcaffe.so和libcaffe.a，我也想把caffe作为lib放到自己的工程中，使用libcaffe.so工程运行没问题，但用静态库libcaffe.a时会发生链接错误，研究了几天也没查出来什么原因。请问你这个repo生成的libcaffe.a和caffe源码自己生成的libcaffe.a的不同之处在哪里呢？

~~另外如果用GPU的话CUDA怎么办?~~（貌似已经支持了？）多谢！

**Comment by 10km** [comment]
生成的静态库没啥不同，只是编译方式不同造成连接参数有很多不同，你真要对比，可以运行这个脚本，对比生成的Makefile中的连接参数与你的有什么不同才知道。
windows下的powershell目前 可以支持GPU编译，但需要用户自己确保CUDA安装正确。

非常抱歉，才看到你的问题，
github国内访问偏慢，我现在不常上来。主要是用国内的gitee( https://gitee.com/l0km/caffe-static )，有问题可以发到那里，我才能及时看到。
