### ISSUE TITLE
CPU和GPU

### ISSUE THREAD

**Issue by 743341** [10km/caffe-static#3]
请问caffe是CPU-ONLY版本吗？如何设置安装支持GPU版本caffe？谢谢。

**Comment by 10km** [comment]
caffe-static是一套windows/linux脚本，设计的目的是实现全自动的caffe库静态编译，
caffe-static的脚本默认编译出的是CPU-ONLY版本，没有GPU版本，因为编译GPU版本需要手工安装CUDA （CUDA没办法自动安装），所以没办法做成自动化的脚本，
所以脚本目前默认是不支持CPU编译的
但是在windows下的powershell脚本中我做了尝试，在windows系统已经正确安装了cuda的情况下，通过指定-caffe_gpu -caffe_cudnn_root 等参数，可以编译出GPU版本，具体参见 -help
国内访问github偏慢，我不常上github,有问题，我主要用国内的gitee仓库( https://gitee.com/l0km/caffe-static ),有问题发到那里我能及时看到。

**Comment by 743341** [comment]
好的，谢谢
